### ISSUE TITLE
Search and Inference

### ISSUE THREAD

**Issue by ghost** [ggjy/HitDet.pytorch#2]
@ggjy Thank you for your hard work,

- Will the architecture search code and documentation be released?
- How to predict a single image using your trained model?

**Comment by ggjy** [comment]
We are not going to open source the searching code recently.
You can use the tools/test.py to predict single image,
```
python tools/test.py --config CONFIG --checkpoint CHECKPOINT --out OUTPUT.pkl --show --eval bbox
```
and change the dataset path in config file.

**Comment by ghost** [comment]
Have you tested limiting the flops below 50B mark?
How does your model performance compare tho EfficientDet?

**Comment by ggjy** [comment]
We use the soft constraints (added loss) when searching the architecture, with the input size e.g. 1333x800 we can't get 50B FLOPs. We have comparable results with EfficientDet.
