### ISSUE TITLE
Search cost

### ISSUE THREAD

**Issue by tingtingliangvs** [ggjy/HitDet.pytorch#3]
Hi there, thanks for sharing your work! It's very inspiring. I have a question for searching time cost, which is not specified in your paper. Would you please tell me an approximate number, for example, how many GPU days? Thanks a lot!

**Comment by ggjy** [comment]
In the end-to-end search phrase (e.g. backbone has its 8 candidates, neck has its 8 candidates, head has its 8 candidates), it takes ~15h to seach the final architecture (12 epochs) on 8 V100 GPUs.
